const nodemailer = require('nodemailer');
const path = require('path');
const dns = require('dns');

// ─── Create transporter (nodemailer v8 compatible) ────────────────────────────
const createTransporter = () => {
  return nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false, // TLS (STARTTLS)
    pool: true,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS || process.env.EMAIL_PASSWORD, // Support both
    },
    // 🔥 FORCE IPv4: The "Nuclear Option" for Render network issues
    family: 4, 
    lookup: (hostname, options, callback) => {
      dns.lookup(hostname, { family: 4 }, (err, address, family) => {
        callback(err, address, family);
      });
    },
    tls: {
      ciphers: 'SSLv3',
      rejectUnauthorized: false
    },
    connectionTimeout: 20000,
    greetingTimeout: 20000,
    socketTimeout: 20000,
    dnsTimeout: 10000
  });
};

// ─── Severity helpers ──────────────────────────────────────────────────────────
const SEVERITY_COLORS = { low: '#28a745', medium: '#ffc107', high: '#dc3545' };
const SEVERITY_EMOJIS = { low: '🟢', medium: '🟡', high: '🔴' };
const CRACK_LABELS = {
  hairline: 'Hairline Crack',
  surface: 'Surface Crack',
  structural: 'Structural Crack',
};

// ─── Send Snag Report Email to Contractor ─────────────────────────────────────
const sendSnagReportEmail = async ({ contractorEmail, contractorName, snagData, customSubject, customBody, userId }) => {
  const { pool } = require('../config/db'); // Import here to avoid circular dep
  
  try {
    const transporter = createTransporter();

    const crackLabel = CRACK_LABELS[snagData.crack_type] || snagData.crack_type || 'Unknown';
    const severityLabel = (snagData.severity || 'Minor').charAt(0).toUpperCase() + (snagData.severity || 'Minor').slice(1);
    
    // Default Recommendation logic
    let recommendation = "No damage detected. No action required.";
    if (severityLabel === "Low" || severityLabel === "Minor") recommendation = "Minor issue detected. Regular monitoring is advised.";
    else if (severityLabel === "Medium" || severityLabel === "Moderate") recommendation = "Moderate damage detected. Maintenance is recommended to prevent escalation.";
    else if (severityLabel === "High" || severityLabel === "Severe") recommendation = "Severe damage detected. Immediate repair action is required.";

    const imageFilename = snagData.image_url ? path.basename(snagData.image_url) : 'No image provided';
    
    // ─── Default Email Body ───
    const defaultBodyText = `
====================================
     AI INSPECTION NOTIFICATION
====================================

Dear ${contractorName},

The AI-powered inspection system has successfully analyzed the provided image for project ${snagData.project_name || 'N/A'}.

------------------------------------

Snag ID        : ${snagData.snag_code}
Image Name     : ${imageFilename}
Damage Type    : ${crackLabel}
Severity Level : ${severityLabel}
Location       : ${snagData.location_desc}

------------------------------------

Recommendation:
${recommendation}

------------------------------------

The detailed inspection report has been generated and is attached with this email.

Attachment: inspection_report.txt

------------------------------------

Regards,
AI Snag Detection System
    `;

    // ─── Generate Default Report Content ───
    const defaultReportContent = `
==============================
   BUILDING DAMAGE REPORT
==============================

Date: ${new Date().toLocaleString()}

--------------------------------
Snag ID        : ${snagData.snag_code}
Image Analyzed : ${imageFilename}
Damage Type    : ${crackLabel}
Severity Level : ${severityLabel}
Location       : ${snagData.location_desc}
--------------------------------

Recommendation:
${recommendation}

--------------------------------
Generated by AI Snag Detection System
`;

    const finalSubject = customSubject || `🚨 [${severityLabel.toUpperCase()}] Building Damage Inspection Report – ${snagData.snag_code}`;
    const finalText = customBody || defaultBodyText;

    const info = await transporter.sendMail({
      from: `"Snag Detection System" <${process.env.EMAIL_FROM || process.env.EMAIL_USER}>`,
      to: contractorEmail,
      subject: finalSubject,
      text: finalText,
      attachments: [
        {
          filename: 'inspection_report.txt',
          content: defaultReportContent,
        }
      ]
    });

    console.log(`✅ Report email sent to ${contractorEmail} | messageId: ${info.messageId}`);
    
    // ─── LOG TO DATABASE ───
    try {
      await pool.query(
        `INSERT INTO mail_logs (recipient, subject, content, snag_id, user_id, status)
         VALUES ($1, $2, $3, $4, $5, 'sent')`,
        [contractorEmail, finalSubject, finalText, snagData.snag_id, userId]
      );
    } catch (dbErr) {
      console.error('⚠️ Failed to log email to database:', dbErr.message);
    }

    return { success: true, messageId: info.messageId };

  } catch (error) {
    console.error(`❌ Report email failed: ${error.message}`);
    return { success: false, error: error.message };
  }
};

// ─── Send Status Update Email to Site Engineer ────────────────────────────────
const sendStatusUpdateEmail = async ({ engineerEmail, engineerName, snagData, newStatus }) => {
  try {
    const transporter = createTransporter();

    const statusMap = {
      in_progress: { label: 'In Progress 🔧', color: '#ffc107', msg: 'The contractor has started working on this snag.' },
      resolved: { label: 'Resolved ✅', color: '#28a745', msg: 'The contractor has marked this snag as resolved. Please verify the fix on site.' },
    };
    const s = statusMap[newStatus] || { label: newStatus, color: '#6c757d', msg: 'Status has been updated.' };

    const html = `
      <!DOCTYPE html>
      <html>
      <body style="font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:20px;">
        <div style="max-width:600px;margin:auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 10px rgba(0,0,0,.1);">
          <div style="background:#1a1a2e;color:#fff;padding:24px;text-align:center;">
            <h2 style="margin:0;">🏗️ Snag Status Update</h2>
          </div>
          <div style="padding:28px;">
            <p>Dear <strong>${engineerName}</strong>,</p>
            <p>The status of snag <strong>${snagData.snag_code}</strong> has been updated.</p>
            <div style="background:#f8f9fa;border-left:4px solid ${s.color};padding:16px;border-radius:4px;font-size:13px;">
              <p><strong>Snag ID:</strong> ${snagData.snag_code}</p>
              <p><strong>Location:</strong> ${snagData.location_desc}</p>
              <p><strong>New Status:</strong> <span style="color:${s.color};font-weight:bold;">${s.label}</span></p>
            </div>
            <p style="margin-top:16px;">${s.msg}</p>
          </div>
          <div style="background:#f8f9fa;padding:14px;text-align:center;font-size:11px;color:#888;">
            <p>© ${new Date().getFullYear()} Snag Detection Platform</p>
          </div>
        </div>
      </body>
      </html>
    `;

    const info = await transporter.sendMail({
      from: `"Snag Detection System" <${process.env.EMAIL_FROM || process.env.EMAIL_USER}>`,
      to: engineerEmail,
      subject: `📋 Snag ${snagData.snag_code} Status Updated → ${s.label}`,
      html,
    });

    console.log(`✅ Status email sent to ${engineerEmail} | messageId: ${info.messageId}`);
    return { success: true, messageId: info.messageId };

  } catch (error) {
    console.error(`❌ Status email failed: ${error.message}`);
    return { success: false, error: error.message };
  }
};

// ─── Send OTP Email (Secure Verification) ───────────────────────────────────────
const sendOTPEmail = async (email, otp) => {
  try {
    const transporter = createTransporter();

    const html = `
      <!DOCTYPE html>
      <html>
      <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7f6; margin: 0; padding: 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f4f7f6; padding: 40px 0;">
          <tr>
            <td align="center">
              <table width="400" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
                <tr style="background: linear-gradient(135deg, #1C1208, #3A2410);">
                  <td align="center" style="padding: 30px;">
                    <h2 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 1px;">SnagDetect</h2>
                    <p style="color: rgba(255,255,255,0.7); margin-top: 5px; font-size: 14px;">Verification Portal</p>
                  </td>
                </tr>
                <tr>
                  <td style="padding: 40px; text-align: center; color: #333333;">
                    <p style="font-size: 16px; margin-bottom: 25px;">Hello,</p>
                    <p style="font-size: 15px; line-height: 1.5; color: #666;">To complete your contractor registration, please use the following one-time password (OTP):</p>
                    <div style="background-color: #f8f9fa; border: 1px dashed #d97706; padding: 20px; border-radius: 8px; margin: 30px 0;">
                      <span style="font-size: 32px; font-weight: 800; letter-spacing: 10px; color: #d97706;">${otp}</span>
                    </div>
                    <p style="font-size: 12px; color: #999; margin-top: 30px;">This code is valid for <strong>5 minutes</strong>. Do not share this with anyone.</p>
                  </td>
                </tr>
                <tr style="background-color: #fafbfc; border-top: 1px solid #eeeeee;">
                  <td align="center" style="padding: 20px; color: #999; font-size: 11px;">
                    <p>© ${new Date().getFullYear()} Snag Detection AI Platform.<br/>All rights reserved.</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
      </html>
    `;

    const info = await transporter.sendMail({
      from: `"SnagDetect Verification" <${process.env.EMAIL_FROM || process.env.EMAIL_USER}>`,
      to: email,
      subject: `🗝️ ${otp} is your verification code for SnagDetect`,
      html,
    });

    console.log(`✅ OTP email sent to ${email} | messageId: ${info.messageId}`);
    return { success: true };

  } catch (error) {
    console.error(`❌ OTP email failed: ${error.message}`);
    return { success: false, error: error.message };
  }
};

module.exports = { createTransporter, sendSnagReportEmail, sendStatusUpdateEmail, sendOTPEmail };
